config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :users, only: [:index, :show, :update] do
      resources :skills, only: [:create]
      resources :projects, only: [:create]
      resources :experiences, only: [:create]
      end
      resources :skills, only: [:show, :update, :destroy]
      resources :projects, only: [:show, :update, :destroy]
      resources :experiences, only: [:show, :update, :destroy]
      post "/skills", to: "skills#update_positions"
      post "/projects", to: "projects#update_positions"
      post "/experiences", to: "experiences#update_positions"
    end
  end

  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :users, only: [:index, :show, :update] do
    resources :skills, only: [:create]
    resources :projects, only: [:create]
    resources :experiences, only: [:create]
    get "/showcase", to: "users#showcase"
  end
  resources :skills, only: [:update, :destroy]
  resources :projects, only: [:update, :destroy]
  resources :experiences, only: [:update, :destroy]
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar">
    <h1><%= link_to "FreeMe.", root_path, class: "logo" %></h1>
    <ul class="nav-links">
      <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to "profile", user_path(current_user) %>
        </li>
        <li class="nav-item">
          <%= link_to "showcase", user_showcase_path(current_user), target: :_blank %>
        </li>
        <li class="nav-item">
          <%= link_to "Log out", destroy_user_session_path, method: :delete %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path %>
        </li>
      <% end %>
    </ul>
</nav>

app/views/shared/_showcase.html.erb
<div class="sc-main-container">
<!-- navbar -->
  <div class="sc-navbar">
    <h1 class="sc-logo"><%= @user.full_name %></h1>
    <ul class="sc-nav-links">
      <% if current_user == @user %>
        <li class="sc-nav-item">
            <%= link_to "profile", user_path(current_user) %>
        </li>
      <% end %>
      <li class="sc-nav-item"><a href="<%= @user.cv %>" target="_blank">CV</a></li>
      <li class="sc-nav-item"><a href="#aboutModal" data-toggle="modal" data-target="#aboutModal">About</a></li>
    </ul>
  </div>
<!-- end of navbar -->

<!-- banner section contains profile pic and headline -->
  <div class="sc-banner-container">
    <div class="sc-banner-title">
      <h1>Hi, I'm <%= @user.first_name %>.</h1>
      <h2 style="font-size: 24px; color: slategray;"><%= @user.headline %></h2>
      <% if @user.available? %>
        <h3>Available for hire</h3>
      <% else %>
        <h3>Available soon</h3>
      <% end %>
    </div>
    <div class="sc-profile-pic">
      <% if @user.photo.attached? %>
          <%= cl_image_tag @user.photo.key, class: "sc-profile-pic" %>
        <% else %>
          <%= image_tag "avatar.svg", class: "sc-profile-pic" %>
        <% end %>
    </div>
  </div>
<!-- end of banner section -->

<!-- skills section below -->
  <h1 class="sc-cont-header">Skills</h1>
  <div class="sc-skills-container">
    <div class="sc-skills-grid">
      <% @skills.each do |skill| %>
      <div class="pr-skills-card">

                  <div class="pr-skills-info">

                    <div class="skill-img-header">
                      <%= cl_image_tag skill.icon.photo.key, class:'skill-img' %>
                      <h2> <%= skill.skill_name %></h2>
                    </div>
                    <h6 style="color: slategray">Level</h6>
                    <div id="progress-bar">
                      <% if skill.level == 'novice' %>
                        <p class="progress-bar" id="nov"> </p>
                      <% end -%>

                      <% if skill.level == 'advanced-beginner' %>
                        <p class="progress-bar" id="advb"></p>
                      <% end -%>

                      <% if skill.level == 'competent' %>
                        <p class="progress-bar" id="comp"></p>

                      <% end -%>

                      <% if skill.level == 'proficient' %>
                        <p class="progress-bar" id="pro"></p>
                      <% end -%>

                      <% if skill.level == 'expert' %>
                        <p class="progress-bar" id="exp"></p>
                      <% end -%>
                    </div>
                    <% if skill.years_of_experience == 0 %>
                      <h6 id="skill-exp"><strong>Experience:</strong> less than one year</h6>
                    <% elsif skill.years_of_experience == 1 %>
                      <h6 id="skill-exp"><strong>Experience:</strong> <%= skill.years_of_experience %> year</h6>
                    <% else %>
                      <h6 id="skill-exp"><strong>Experience:</strong> <%= skill.years_of_experience %> years</h6>
                    <% end %>
                  </div>
                </div>
      <!-- <div class="sc-skills-card">
        <h5><%= skill.skill_name %></h5>
        <h6>Years: <%= skill.years_of_experience %></h6>
        <p><%= skill.level %></p>
      </div> -->
      <% end %>
    </div>
  </div>
<!-- end of skills section -->

<!-- projects section below -->
  <h1 class="sc-cont-header">Projects</h1>
  <div class="sc-projects-container">
    <% @projects.each do |project| %>
    <div class="sc-project-card">
      <div class="sc-project-card-body">
        <h2><%= project.title %></h2>
        <p><%= project.description %></p>
      </div>
      <div class="sc-project-card-img">
        <%= cl_image_tag project.photo.key, class: 'sc-project-card-img' %>
      </div>
    </div>
    <% end %>
  </div>
<!-- end of projects section -->

<!-- experience section -->
<h1 class="sc-cont-header-exp">Experience</h1>
<div class="sc-exp-container">
  <div class="sc-exp-grid">
    <% @experiences.each do |experience| %>
    <div class="sc-exp-card">
      <!-- <div class="sc-exp-card-img">
        <%= cl_image_tag experience.photo.key, class: 'sc-exp-card-img' %>
      </div> -->
      <div class="sc-exp-card-body">
        <h2><%= experience.role %></h2>
        <h3><%= experience.company %>, <%= experience.location %></h3>
        <p><%= experience.summary %></p>
        <% if experience.end_date == nil %>
          <p class="sc-exp-card-body-date">
            <%= experience.start_date.strftime("%B %Y") %> to Present</p>
        <% else %>
          <p class="sc-exp-card-body-date">
            <%= experience.start_date.strftime("%B %Y") %>
            to <%= experience.end_date.strftime("%B %Y") %></p>
        <% end %>
      </div>
    </div>
    <% end %>
  </div>
</div>
<!-- end of experience section -->

<!-- about section -->
<div class="modal fade" id="aboutModal" tabindex="-1" role="dialog" aria-labelledby="aboutModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div id="sc-modal-header" class="modal-content">
      <div id="sc-modal-header" class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">About <%= @user.full_name %></h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div id="sc-modal-body" class="modal-body">
        <%= @user.about %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>


<!-- end of about section -->
  
</div>

<!-- footer section -->
  <div class="sc-footer">
    <h5>LET'S CONNECT</h5>
    <h2>Want to know more or collaborate?</h2>
    <h2>Get in touch.</h2>
    <h5><%= @user.email %></h5>
  </div>
<!-- end of footer section -->

app/views/shared/_whattodo.html.erb
<% unless @user.profile_finished? %>
  <div class="pr-cont-header">
    <h1>Building your showcase</h1>
  </div>
  <div class="pr-whattodo-container">
    <div class="whattodo-header">
      <% if @user.profile_empty? %>
        <h2>Welcome to freeme! Let's get you started.</h2>
      <% else %>
        <h2>Great start. Keep going!</h2>
      <% end %>
    </div>
    <% if @skills != nil %>
      <% if @skills.length < 1 %>
        <div class="whattodo-div">
          <h2>🤐 Add some skills</h2>
          <h3>Add some of the amazing skills you've learned during your bootcamp.
              click on the plus button and add your first skill.</h1>
        </div>
      <% end %>
      <% if @skills.length == 1 %>
        <div class="whattodo-div">
          <h2>🧐 Add some more skills</h2>
          <h3>Keep adding skills. You can never have too many.</h1>
        </div>
      <% end %>
    <% end%>
    <% if @projects!= nil %>
      <% if @projects.empty? %>
        <div class="whattodo-div">
          <h2>💪 Add some projects</h2>
          <h3>Show some of the projects that you've worked on.
              Big or small.</h1>
        </div>
      <% end %>
      <% if @projects.length == 1 %>
        <div class="whattodo-div">
          <h2>😎 Add some more projects</h2>
          <h3>You can even add that css race game you made back in week 3 of your bootcamp.</h1>
        </div>
      <% end %>
    <% end %>
    <% if @experiences != nil %>
      <% if @experiences.empty? %>
        <div class="whattodo-div">
          <h2>👢 Add some experience</h2>
          <h3>Finishing a bootcamp is a massive achievement. Add it now!</h1>
        </div>
      <% end %>
      <% if @experiences.length == 1 %>
        <div class="whattodo-div">
          <h2>🚀 Add some more experience</h2>
          <h3>Doesn't even have to be code related. All experience counts!</h1>
        </div>
      <% end %>
    <% end %>
  </div>
<% end %>